### ISSUE TITLE
增加香港、澳门、台湾出现的问题

### ISSUE THREAD

**Issue by moahmn** [tshi0912/city-picker#10]
香港、澳门、台湾下好像没有对应的code？ 然后我尝试着在省级放香港、澳门、台湾，发现如果只有一级的话点击了香港（或者任意一个）后、剩余的两个再点击都没有响应

**Comment by moahmn** [comment]
问题解决了。。。原来你都写了香港澳门台湾了，只是隐藏了= = 我还看了好久你代码

**Comment by tshi0912** [comment]
@moahmn 对的:)
