### ISSUE TITLE
新手请问如何取得选取后的值？

### ISSUE THREAD

**Issue by weishijun14** [tshi0912/city-picker#11]
我在做一个网站，然后用到您的插件，想请假选取了地址之后，如何获得我选的值？
不太清楚操作，恳请大牛能说详细点，谢谢！

**Comment by tshi0912** [comment]
$('input').val()发自网易邮箱大师
            在2016年07月28日 22:43，weishijun14 写道:我在做一个网站，然后用到您的插件，想请假选取了地址之后，如何获得我选的值？
不太清楚操作，恳请大牛能说详细点，谢谢！

**Comment by xiaohua1001** [comment]
$('#fromCityName').citypicker();
            //获取省份的值
            var aa=$("#fromCityName").next().find('span[data-count="province"]').attr('data-code');
            alert(aa);
            //获取城市的值
            var bb=$("#fromCityName").next().find('span[data-count="city"]').attr('data-code');
            alert(bb);
            //获取区县的值
            var cc=$("#fromCityName").next().find('span[data-count="district"]').attr('data-code');
            alert(cc);

**Comment by tshi0912** [comment]
v1.1.0新增了获取Code的功能，具体使用请参考如下：

// type 可以是: null或undefined(获取完整的code，以/分隔)、province(获取province的code)、city(获取city的code)、district(获取district的code)
$('.city-picker').data('citypicker').getCode(type);
