### ISSUE TITLE
getText:方法是不是会执行多次

### ISSUE THREAD

**Issue by zhouweiaccp** [tshi0912/city-picker#2]
效率上，是不是存在这个问题

**Comment by zhouweiaccp** [comment]
在output:function()中 ，数据异步取，然后在执行$select.html($this.getList(data, type))。【产生的html无元素，在bind 中是无法执行，】原因是什么？？【我的解决 方法是，在新的html后面加事件处理】

**Comment by tshi0912** [comment]
其实地址元素的事件绑定都是委托在dropdown上的，只要异步渲染之前dropdown已经存在就不会有这个问题啦。
