### ISSUE TITLE
可否增加监听地址改变的onchange回调事件

### ISSUE THREAD

**Issue by 2lei** [tshi0912/city-picker#20]
类似mobiscroll api中onchange，或者onclosed这样的event
![ecds794 oj7 80nojp5j4](https://cloud.githubusercontent.com/assets/12872293/18866711/bfe7188c-84d3-11e6-9a4f-1d3f52981a74.png)

**Comment by tshi0912** [comment]
地址改变会触发`cp:updated`事件

**Comment by philwu** [comment]
所以……就是不能的意思吗？

**Comment by tshi0912** [comment]
@philwu 在input域上监听cp:update事件，就能获得地址改变回调。

**Comment by lovedreamland** [comment]
我自己改的：
在feedVal函数中，增加回调：
feedVal: function (trigger) {
        	var completeFun = this.$element.attr("completeFun");
        	if(completeFun != undefined){
    			completeFun = window[completeFun];
    			if (typeof(completeFun) === 'function') {
    				try{
    					completeFun();
    				}catch(e){
    					window.onload = function(){
    						completeFun();
    					}
    				}
    			}
    		}
            this.$element.val(this.getVal());
            if(trigger) {
                this.$element.trigger('cp:updated');
            }
        },

调用：
<input readonly id="city-picker" name="city-picker" type="text" data-toggle="city-picker" style="width:380px;" completeFun="getAddress"/>

function getAddress(){

}

**Comment by tshi0912** [comment]
@lovedreamland 用事件的方式比传入回调藕合性要更低

**Comment by ivantree** [comment]
在input域上监听cp:update事件，就能获得地址改变回调。 有没有具体的示例呢

**Comment by philwu** [comment]
要是有个"on:clicked"事件就好了。在用户选了同一个数值的时候,on:updated好像不会被触发。本想研究一下源代码自己写一个，无奈水平太低……而且从没写过JQuery插件……
