### ISSUE TITLE
这几个数据，可能有问题，会引起递归循环错误。

### ISSUE THREAD

**Issue by yuankeyan** [tshi0912/city-picker#26]
"460200" : {
        "460200" : "三亚湾",
"441900" : {
        "441900" : "三元里"
    },
    "442000" : {
        "442000" : "湖滨北路"
    }
这几个数据，可能有问题，会引起递归循环错误。

**Comment by tshi0912** [comment]
谢谢，已修正：
"460200" : {
"460201" : "三亚湾",
"441900" : {
"441901" : "三元里"
},
"442000" : {
"442001" : "湖滨北路"
}
