### ISSUE TITLE
如何取值？

### ISSUE THREAD

**Issue by PaulXsl** [tshi0912/city-picker#4]
我试过getVal()和getText()等方法，可都不好使，change事件也没有响应，首页的文档里也没有提到这些，可否给一个如何取值的例子？谢谢！

**Comment by lyz19890927** [comment]
something like $('#city-selector').val()

**Comment by tshi0912** [comment]
@lyz19890927 正解

**Comment by PaulXsl** [comment]
多谢楼上两位！有没有直接获取id的方法呢？

**Comment by nevermo2013** [comment]
@tshi0912 只能取到文本，取不到code

**Comment by lyz19890927** [comment]
@nevermo2013 办法是有的，比如`var _district = $('span[data-count="district"]').html();
		var _districtCode= $('span[data-count="district"]').attr('data-code');`这样可以取到区县的文本和code

**Comment by xiaohua1001** [comment]
$('#fromCityName').citypicker();
            //获取省份的值
            var aa=$("#fromCityName").next().find('span[data-count="province"]').attr('data-code');
            alert(aa);
            //获取城市的值
            var bb=$("#fromCityName").next().find('span[data-count="city"]').attr('data-code');
            alert(bb);
            //获取区县的值
            var cc=$("#fromCityName").next().find('span[data-count="district"]').attr('data-code');
            alert(cc);

**Comment by tshi0912** [comment]
v1.1.0新增了获取Code的功能，具体使用请参考如下：

// type 可以是: null或undefined(获取完整的code，以/分隔)、province(获取province的code)、city(获取city的code)、district(获取district的code)
$('.city-picker').data('citypicker').getCode(type);

**Comment by alex521** [comment]
有没有事件来知道用户已经选择完了

**Comment by tshi0912** [comment]
`$('input').on('cp:updated',function(){
   // your code
})`
