### ISSUE TITLE
可以变成选择某一省份中多个市级选项吗？

### ISSUE THREAD

**Issue by Tony1952466760** [tshi0912/city-picker#41]
我现在又这样的一个需求，我指定了特定的省份，那么在选择市级选项时，是否可以选择多个?比如我指定江西省，那么在市级选择中我可以选择南昌、九江。。。。。一起选择。
![image](https://cloud.githubusercontent.com/assets/11804148/26195289/d6a92d04-3bed-11e7-8703-f07dc6ec20ce.png)

**Comment by tshi0912** [comment]
目前不支持多选
