### ISSUE TITLE
和JQuery的DataTables在同一页面使用，调用不到重置函数--citypicker('destroy')。

### ISSUE THREAD

**Issue by walkenola** [tshi0912/city-picker#5]
和JQuery的DataTables在同一页面使用，调用不到重置函数--citypicker('destroy')。两者都需要引用一个jquery.js，是不是冲突了，如果是的话，该怎么办呢？

**Comment by tshi0912** [comment]
不会冲突的，你调用不到destroy方法，能否给出更详细的信息？

**Comment by tshi0912** [comment]
帅哥，如果没有问题的话，我就关闭啦!
