### ISSUE TITLE
请问回掉函数在哪里？span是否多余？

### ISSUE THREAD

**Issue by imsole** [tshi0912/city-picker#53]
1、当如选择完成以后，时候可以添加一个回掉函数？
2、既然是插件，文本框就应该是客户端自己来定义，插件不用定义吧，感觉span是多余的。

**Comment by tshi0912** [comment]
1. 通过 cp:updated 事件通知完成
2. 添加span是为了用来渲染分隔符样式的，获取的值不会有span。

**Comment by ash0080** [comment]
偷懒的话，直接在css里把 .city-picker-input 的样式移除， .city-picker-span display:none 隐藏掉即可，现在用span替换掉原始input的方式的确不太友好，另外dropList的位置计算也有些问题，不改变原生input的情况下， 可以直接跟在原生element下面
