### ISSUE TITLE
在模态对话框中下拉框不能显示全，怎么解决？

### ISSUE THREAD

**Issue by yuankeyan** [tshi0912/city-picker#6]
![Uploading QQ20160601-0@2x.png…]()

**Comment by tshi0912** [comment]
看不到你的图，猜测是modal框外围的css设置了overflow:hidden，请将CSS重置为overflow:auto试试看。

**Comment by yuankeyan** [comment]
谢谢，已经解决了，提个建议，是否可以内置一个清空功能，这样更方便使用
