### ISSUE TITLE
当把放有city-picker的form-horizontal放入collapse中时，city-picker样式会出现变形

### ISSUE THREAD

**Issue by lmtoo** [tshi0912/city-picker#7]
当把放有city-picker的form-horizontal放入collapse中时，city-picker样式会出现变形
`<span class="city-picker-span" style="width:1841px;height:34px;line-height:33px;"><span class="placeholder" style="display: none;">点击从下拉面板中选择省/市</span><span class="title" style="display: inline;"><span class="select-item" data-count="province" data-code="130000">河北省</span>/<span class="select-item" data-count="city" data-code="130300">秦皇岛市</span></span><div class="arrow"></div></span>`
生成的city-picker-span的style的width竟然达到了1841px

**Comment by tshi0912** [comment]
可以在外面方式放置一个div, 通过CSS控制外面DIV的宽度
