### ISSUE TITLE
请问如何通过js修改省市区的值?

### ISSUE THREAD

**Issue by yang22zhang** [tshi0912/city-picker#8]
ajax请求后,获得需要选中的省市区内容,此时应如何修改citypicker的选中值?有没有对应方法?如何调用?

**Comment by lyz19890927** [comment]
比如`$('#areaName').val(data.areaName).citypicker();`

**Comment by yang22zhang** [comment]
@lyz19890927  能否有个具体的例子,这个比较模糊,谢谢.

**Comment by iHelin** [comment]
两个都试过了，怎么选不中啊，input里面也是空的

**Comment by iHelin** [comment]
@lyz19890927 两个都试过了，怎么选不中啊，input里面也是空的

**Comment by tshi0912** [comment]
重新设置input的值后，需要调用下refresh方法进行重绘：
------------------------------------------------------------------------
 $('#areaName').val('湖南省/长沙市/开福区');
 $('#areaName').citypicker('refresh');
//或者
$('#areaName').trigger('change');
