### ISSUE TITLE
这个项目以前是有四级联动的吧

### ISSUE THREAD

**Issue by wblbird** [tshi0912/city-picker#83]
咋没了啊，虽然四级联动数据就大了，但600k也勉强可以接受，五级联动那数据量单json是没法做了。强烈建议，大哥四级联动加个配置项，也增加上

**Comment by tshi0912** [comment]
一直是只到三级联动

**Comment by wblbird** [comment]
其他渠道拿到的代码，跟你这个基本一样，他4级的。

**Comment by DrayChou** [comment]
请问有没有办法可以简单的扩充到四级或者五级？
谢谢
