### ISSUE TITLE
像直辖市，是不是应该只有北京市/东城区   而不是北京市/北京市/东城区??

### ISSUE THREAD

**Issue by moahmn** [tshi0912/city-picker#9]

**Comment by tshi0912** [comment]
这个也是没办法，直辖市下面直接就是区县，没有地市，但是又不能破坏结构，也只能这么处理。发自网易邮箱大师
            在2016年07月11日 10:54，moahmn 写道:

**Comment by khan-lau** [comment]
json树状结构不是更适合描述这种层级关系么.

**Comment by tshi0912** [comment]
这个和树状结构没有太大关系，主要是由于省份 / 城市 /区县 这样个固定三层关系决定的，北京市/东城区这样的数据没法在三层关系的里面直接落地，所以只能折衷取值为北京市/北京市/东城区。
